apiVersion: v1
kind: Service
metadata:
  annotations:
    io.cilium/global-service: "true"
  name: global-debugtools
  namespace: debugtools
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: debugtools
  sessionAffinity: None
  type: ClusterIP
