apiVersion: v1
kind: Namespace
metadata:
  name: luan
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: debugtools
  name: debugtools
  namespace: luan
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: debugtools
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: debugtools
    spec:
      containers:
      - image: luanguimaraesla/debugtools:latest
        imagePullPolicy: Always
        name: ubuntu
        resources:
          limits:
            cpu: 500m
            memory: 300Mi
          requests:
            cpu: 150m
            memory: 150Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_ADMIN
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
